[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presales = "HE51UM7EXK13RDxCZvmcwsf18E4aGCZZRemq5qDKAaHh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run mocha tests/**/*.js"
